name: build
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USER }}" --password-stdin
      - name: Build & push (multi-arch)
        run: |
          IMAGE=ghcr.io/acdcars/app:latest
          docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE --push .